Update file_rotate_create_correctness test

diff --git a/bin/cohort b/bin/cohort
--- a/bin/cohort
+++ b/bin/cohort
@@ -1,23 +1,4 @@
-#!/usr/bin/env sh
-
-# USAGE
-#    cohort [-s <string>]
-#
-# DESCRIPTION
-#    Prints a simple table that provides a cohort analysis of test
-#    results across all tests and all versions for a single subject.
-#
-# OPTIONS
-#    -s [subject] The test subject (Ex: vector,fluentbit,splunk_universal_forwarder,etc)
-#
-# EXAMPLES
-#    ./cohort -s vector
-#
-#    Vector Bechmark Cohort Analysis - avg (quantity)
-#    ------------------------------------------------
-#    name                       | v0.1.0-alpha.5-17-geb59a3f
-#    ---------------------------|---------------------------
-#    tcp_to_blackhole (default) | 6.2s (5)    
+#!/usr/bin/env sh 
 
 #
 # Setup
@@ -34,14 +15,14 @@ set -o errexit -o pipefail -o noclobber -o nounset
 
 usage="
 USAGE
-   cohort [-s <string>]
+   cohort [-s subject]
 
 DESCRIPTION
    Prints a simple table that provides a cohort analysis of test
    results across all tests and all versions for a single subject.
 
 OPTIONS
-   -s [subject] The test subject (Ex: vector,fluentbit,splunk_universal_forwarder,etc)
+   -s  The test subject (Ex: vector,fluentbit,splunk_universal_forwarder,etc)
 
 EXAMPLES
    ./cohort -s vector
@@ -54,6 +35,13 @@ EXAMPLES
 "
 
 #
+# Functions
+#
+
+error() { echo "\033[0;31m$1\033[0m"; }
+usage() { echo "$usage" 1>&2; }
+
+#
 # Helpers
 #
 
@@ -64,8 +52,6 @@ my_dir="$(dirname "$0")"
 # Flags
 #
 
-usage() { echo "Usage: $0 [-s <string>]" 1>&2; exit 1; }
-
 subject=''
 
 while getopts "s:" o; do
@@ -75,6 +61,7 @@ while getopts "s:" o; do
             ;;
         *)
             usage
+            exit 3
             ;;
     esac
 done
@@ -86,8 +73,9 @@ shift $((OPTIND-1))
 
 if [ -z "$subject" ]
   then
-    echo "Error: you must supply a subject via the -s flag\n$usage"
+    error "Error: you must supply a subject via the -s flag"
     usage
+    exit 3
 fi
 
 #
diff --git a/bin/compare b/bin/compare
--- a/bin/compare
+++ b/bin/compare
@@ -15,19 +15,27 @@ set -o errexit -o pipefail -o noclobber -o nounset
 
 usage="
 USAGE
-   compare
+   compare -t test [-c configuration] [-p]
 
 DESCRIPTION
    Prints a simple table that compares the average test times
    across all subjects on all tests.
 
 OPTIONS
-   -t [test_name] The test name (ex: tcp_to_blackhole,etc)
-   -c [test_configuration] The test configuration (default: default)
+   -c, --configuration  The test configuration (default: default)
+   -p, --percentages    To include percentage increase from test winner (default: false)
+   -t, --test           The test name (ex: tcp_to_blackhole,etc)
 
 EXAMPLES
-   ./compare
+   ./compare -t tcp_to_tcp_performance
 "
+
+#
+# Functions
+#
+
+error() { echo "\033[0;31m$1\033[0m"; }
+usage() { echo "$usage" 1>&2; }
 
 #
 # Dependencies
@@ -36,7 +44,7 @@ EXAMPLES
 # This is required for flag parsing, specifically the posix style: --flag
 ! getopt --test > /dev/null 
 if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
-    echo 'Error: enhanced getopt is not installed. (brew install gnu-getopt)'
+    error 'Error: enhanced getopt is not installed. (brew install gnu-getopt)'
     exit 1
 fi
 
@@ -87,11 +95,22 @@ while true; do
             break
             ;;
         *)
-            echo "Invalid option detected: $1"
+            error "Invalid option detected: $1"
             exit 3
             ;;
     esac
 done
+
+#
+# Requirements
+#
+
+if [ -z "$test_name" ]
+  then
+    error "Error: you must supply a test name via the -t flag"
+    usage
+    exit 3
+fi
 
 #
 # Header
diff --git a/bin/export b/bin/export
--- a/bin/export
+++ b/bin/export
@@ -29,6 +29,13 @@ EXAMPLES
 "
 
 #
+# Functions
+#
+
+error() { echo "\033[0;31m$1\033[0m"; }
+usage() { echo "$usage" 1>&2; }
+
+#
 # Helpers
 #
 
@@ -65,7 +72,7 @@ while true; do
             break
             ;;
         *)
-            echo "Invalid option detected: $1"
+            error "Invalid option detected: $1"
             exit 3
             ;;
     esac
diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -15,41 +15,48 @@ set -o errexit -o pipefail -o noclobber -o nounset
 
 usage="
 USAGE
-   test
+   test -t test [-c configuration] [-s subjects] [-u user-id] [{-b|-r}]
 
 DESCRIPTION
    Runs and profiles the provided case, uploading the results to S3.
 
 OPTIONS
-   -b, --bootstrap-only          Bootstrap the test only, do not test any subjects
-   -c, --configuration           The test configuration (default: default, env: VECTOR_TEST_CONFIGURATION)
-   -r, --run-only                Don't run the bootstrap task, just run the test. This is helpful for repeated runs.
-   -s, --subjects                The test subjects (ex: vector=1.0.0,fluentbit=1.0.0, env: VECTOR_TEST_SUBJECTS)
-   -t, --test                    The test to run (ex: tcp_to_blackhole)
-   -u, --user-id                 Your user ID (ex: ben, env: VECTOR_TEST_USER_ID)
+   -b, --bootstrap-only  Bootstrap the test only, do not test any subjects
+   -c, --configuration   The test configuration (default: default, env: VECTOR_TEST_CONFIGURATION)
+   -r, --run-only        Don't run the bootstrap task, just run the test. This is helpful for repeated runs.
+   -s, --subjects        The test subjects (ex: vector=1.0.0,fluentbit=1.0.0, env: VECTOR_TEST_SUBJECTS)
+   -t, --test            The test to run (ex: tcp_to_blackhole)
+   -u, --user-id         Your user ID (ex: ben, env: VECTOR_TEST_USER_ID)
 
 EXAMPLE
    test -t tcp_to_blackhole -s vector
 "
 
 #
+# Functions
+#
+
+error() { echo "\033[0;31m$1\033[0m"; }
+usage() { echo "$usage" 1>&2; }
+
+#
 # Dependencies
 #
 
 if ! [ -x "$(command -v ansible-playbook)" ]; then
-  echo 'Error: ansible-playbook is not installed. (sudo pip install ansible)' >&2
+  error 'Error: ansible-playbook is not installed. (sudo pip install ansible)' >&2
   exit 1
 fi
 
 if ! [ -x "$(command -v terraform)" ]; then
-  echo 'Error: terraform is not installed. (brew install terraform)' >&2
+  error 'Error: terraform is not installed. (brew install terraform)' >&2
   exit 1
 fi
 
 # This is required for flag parsing, specifically the posix style: --flag
 ! getopt --test > /dev/null 
 if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
-    echo 'Error: enhanced getopt is not installed. (brew install gnu-getopt)'
+    error 'Error: enhanced getopt is not installed. (brew install gnu-getopt)'
     exit 1
 fi
 
@@ -126,7 +133,7 @@ while true; do
             break
             ;;
         *)
-            echo "Invalid option detected: $1"
+            error "Invalid option detected: $1"
             exit 3
             ;;
     esac
@@ -138,26 +145,30 @@ done
 
 if [ -z "$test_configuration" ]
   then
-    echo "Error: you must supply a test configuration via the -c flag:\n$usage"
-    exit 1
+    error "Error: you must supply a test configuration via the -c flag:"
+    usage
+    exit 3
 fi
 
 if [ -z "$test_name" ]
   then
-    echo "Error: you must supply a test name via the -t flag:\n$usage"
-    exit 1
+    error "Error: you must supply a test name via the -t flag:"
+    usage
+    exit 3
 fi
 
 if [ -z "$test_subjects" ]
   then
-    echo "Error: you must supply test subjects via the -s flag:\n$usage"
-    exit 1
+    error "Error: you must supply test subjects via the -s flag:"
+    usage
+    exit 3
 fi
 
 if [ -z "$user_id" ]
   then
-    echo "Error: you must supply a user ID via the -u flag or VECTOR_TESTUSER_ID env var:\n$usage"
-    exit 1
+    error "Error: you must supply a user ID via the -u flag or VECTOR_TESTUSER_ID env var:"
+    usage
+    exit 3
 fi
 
 #
@@ -263,7 +274,8 @@ fi
 #
 
 cd ansible
-extra_vars="test_name=$test_name test_configuration=$test_configuration test_timestamp=$test_timestamp user_id=$user_id $ansible_version_vars"
+test_namespace="tag_TestName_$test_name:&tag_TestConfiguration_$test_configuration:&tag_TestUserID_$user_id"
+extra_vars="test_name=$test_name test_configuration=$test_configuration test_namespace=$test_namespace test_timestamp=$test_timestamp user_id=$user_id $ansible_version_vars"
 
 if [ "$bootstrap" == 'true' ]
 then
